[default_session]
startup_command = 'tmux rename-window editor && nvim'

[[session]]
name='Downloads â¬‡ï¸' 
path='~/Downloads'
startup_command='ls'

[[session]]
name='Nvim config âš™ï¸'
path='~/.config/nvim/'

[[session]]
name="Harro docs ğŸ“"
path='~/Harro-docs/'
